%% @author Alessandro Sivieri <alessandro.sivieri@mail.polimi.it>
%% @doc CREST application behaviour: it starts and stop the application.
%% Autogenerated by MochiWeb.
%% @copyright 2010 Alessandro Sivieri

-module(crest_app).
-behaviour(application).
-export([start/2,stop/1]).

%% External API

%% @doc Start all dependency modules and the CREST application
%% @spec start(atom(), [string()]) -> ok
start(_Type, _StartArgs) ->
    crest_deps:ensure(),
    crest_sup:start_link().

%% @doc Stop the application
%% @spec stop(atom()) -> ok
stop(_State) ->
    ok.
