%% Copyright (c) 2010 Alessandro Sivieri <alessandro.sivieri@mail.polimi.it>
%% 
%% This file is part of CREST-Erlang.
%% 
%% CREST-Erlang is free software: you can redistribute it and/or modify
%% it under the terms of the GNU Lesser General Public License as published by
%% the Free Software Foundation, either version 3 of the License, or
%% (at your option) any later version.
%% 
%% CREST-Erlang is distributed in the hope that it will be useful,
%% but WITHOUT ANY WARRANTY; without even the implied warranty of
%% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%% GNU Lesser General Public License for more details.
%% 
%% You should have received a copy of the GNU Lesser General Public License
%% along with CREST-Erlang. If not, see <http://www.gnu.org/licenses/>.
%% 
%% @author Alessandro Sivieri <alessandro.sivieri@mail.polimi.it>
%% @doc Start module of the CREST server, it initializes all required
%% modules and starts the application.
%% Autogenerated by MochiWeb.
%% @copyright 2010 Alessandro Sivieri

-module(crest).
-export([start/0, stop/0]).

%% External API

%% @doc Initialize all modules and start the application
%% @spec start() -> ok
start() ->
    crest_deps:ensure(),
    ensure_started(crypto),
    application:start(log4erl),
    log4erl:conf("config/log4erl.config"),
    application:start(crest).

%% @doc Stop the application
%% @spec stop() -> ok 
stop() ->
    Res = application:stop(crest),
    application:stop(crypto),
    Res.

%% Internal API

ensure_started(App) ->
    case application:start(App) of
        ok ->
            ok;
        {error, {already_started, App}} ->
            ok
    end.
