{application, crest,
 [{description, "crest"},
  {vsn, "0.1"},
  {modules, [
    crest,
    crest_app,
    crest_demo,
    crest_deps,
    crest_process,
    crest_server,
    crest_sup,
    crest_utils,
    crest_uuid,
    crest_web,
    crest_wordlist
  ]},
  {registered, []},
  {mod, {crest_app, []}},
  {env, []},
  {applications, [kernel, stdlib, crypto]}]}.
