%% @author Alessandro Sivieri <alessandro.sivieri@mail.polimi.it>
%% @doc Start module of the CREST server, it initializes all required
%% modules and starts the application.
%% Autogenerated by MochiWeb.
%% @copyright 2010 Alessandro Sivieri

-module(crest).
-export([start/0, stop/0]).

%% External API

%% @doc Initialize all modules and start the application
%% @spec start() -> ok
start() ->
    crest_deps:ensure(),
    ensure_started(crypto),
    application:start(log4erl),
    log4erl:conf("config/log4erl.config"),
    application:start(crest).

%% @doc Stop the application
%% @spec stop() -> ok 
stop() ->
    Res = application:stop(crest),
    application:stop(crypto),
    Res.

%% Internal API

ensure_started(App) ->
    case application:start(App) of
        ok ->
            ok;
        {error, {already_started, App}} ->
            ok
    end.
